const router = require('express').Router();
const { User } = require('../../models');

// const cloudinary = require("cloudinary").v2;
// const express = require('express');
// const multer = require("multer");



// cloudinary.uploader.upload('./1.png', { tags: 'basic_sample' })
//   .then(function (image) {
//     console.log();
//     console.log("** File Upload (Promise)");
//     console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
//     console.log("* " + image.public_id);
//     console.log("* " + image.url);
//   })
//   .catch(function (err) {
//     console.log();
//     console.log("** File Upload (Promise)");
//     if (err) { console.warn(err); }
//   });

// const cloudinary = require("cloudinary");

router.post('/', async(req, res) => {
    try {
        const userData = await User.create(req.body);


        req.session.save(() => {
            req.session.user_id = userData.id;
            req.session.logged_in = true;

            res.status(200).json(userData);
        });
    } catch (err) {
        res.status(400).json(err);
    }
});


//post route to create user's login
router.post('/login', async (req, res) => {
    console.log('i work',req.body)
    try {
        const userData = await User.findOne({ where: { email: req.body.email } });

        if (req.body.email === "" || !userData) {
            console.log("invalid email or password")
            res
                .status(400)
                .json({ message: 'Incorrect email or password, please try again' });
            return;
        }

        const validPassword = await userData.checkPassword(req.body.password);

        if (!validPassword) {
            res
                .status(400)
                .json({ message: 'Incorrect email or password, please try again' });
            return;
        }
        req.session.save(() => {
            req.session.user_id = userData.id;
            req.session.logged_in = true;
            
            res.json({ user: userData, message: 'You are now logged in!' });
        });
        console.log(req.session)

    } catch (err) {
        console.log(err)
        res.status(400).json(err);
    }
});


//post routes for login 
//within the post route to login - check if the email and password are valid (checkpassword)
//logout post route (destroy)





// router.post('/images', (req, res) => {
//     console.log ('idk')
//     cloudinary.uploader.upload('./1.png', { tags: 'basic_sample' })
//   .then(function (image) {
//     console.log();
//     console.log("** File Upload (Promise)");
//     console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
//     console.log("* " + image.public_id);
//     console.log("* " + image.url);
//   })
//   .catch(function (err) {
//     console.log();
//     console.log("** File Upload (Promise)");
//     if (err) { console.warn(err); }
//   });
//     // console.log(req.file) // to see what is returned to you
//     // const image = {};
//     // image.url = req.file.url;
//     // image.id = req.file.public_id;
//     // Image.create(image) // save image information in database
//     //     .then(newImage => res.json(newImage))
//     //     .catch(err => console.log(err));
// });


module.exports = router;